### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by davidlenz** [benedekrozemberczki/AttentionWalk#1]
I'm getting OOM errors even with small files. The attached file [link_network.txt](https://github.com/benedekrozemberczki/AttentionWalk/files/3100063/link_network.txt) throws the following error:

```
Adjacency matrix powers: 100%|███████████████████████████████████████████████████████| 4/4 [00:00<00:00, 108.39it/s]
Traceback (most recent call last):
  File "src\main.py", line 79, in <module>
    main()
  File "src\main.py", line 74, in main
    model = AttentionWalkTrainer(args)
  File "E:\AttentionWalk\src\attentionwalk.py", line 70, in __init__
    self.initialize_model_and_features()
  File "E:\AttentionWalk\src\attentionwalk.py", line 76, in initialize_model_and_features
    self.target_tensor = feature_calculator(self.args, self.graph)
  File "E:\AttentionWalk\src\utils.py", line 53, in feature_calculator
    target_matrices = np.array(target_matrices)
MemoryError
```
I guess this is due to the large indices of the nodes. Any workarounds for this?

**Comment by benedekrozemberczki** [comment]
Did you index your nodes consecutively? The algorithm has an O(w * |V|^2 ) memory complexity, where w is the window size and V is the node set.

**Comment by benedekrozemberczki** [comment]
You should reindex your nodes starting with zero and index them consecutively.
