### ISSUE TITLE
left_factors and right_factors' size don't match

### ISSUE THREAD

**Issue by sunnyHelen** [benedekrozemberczki/AttentionWalk#2]
Thank you for sharing the code.  
I encounter this error.
![image](https://user-images.githubusercontent.com/28101548/59345110-c7c63080-8d52-11e9-91b9-556da97c6d7e.png)

**Comment by benedekrozemberczki** [comment]
Can you send me the csv file?

**Comment by sunnyHelen** [comment]
Sure. Thank you very much~
https://pan.baidu.com/s/1ZoSCY6ldYdTAbskf8uqk3Q
code is : ps6q

**Comment by benedekrozemberczki** [comment]
I cannot access it send an e-mail.

**Comment by sunnyHelen** [comment]
Ok. I sent the email to you.

**Comment by benedekrozemberczki** [comment]
Can you check whether it is in the format required by the scripts?
