### ISSUE TITLE
can I construct graph from binary matrix?

### ISSUE THREAD

**Issue by sunnyHelen** [benedekrozemberczki/AttentionWalk#3]
Sorry to bother you. 
if I have a binary matrix like this, can I construct graph from this matrix?
![image](https://user-images.githubusercontent.com/28101548/59851012-e2318700-93ae-11e9-93ce-4becc9f874b7.png)

**Comment by benedekrozemberczki** [comment]
Yes You can.

**Comment by FernandoLpz** [comment]
> Sorry to bother you.
> if I have a binary matrix like this, can I construct graph from this matrix?
> ![image](https://user-images.githubusercontent.com/28101548/59851012-e2318700-93ae-11e9-93ce-4becc9f874b7.png)

Hi @sunnyHelen, you can do it by using networkx. 
https://networkx.github.io/documentation/networkx-2.2/reference/generated/networkx.convert_matrix.from_numpy_matrix.html
