### ISSUE TITLE
problem with being killed

### ISSUE THREAD

**Issue by amy-hyunji** [benedekrozemberczki/AttentionWalk#6]
Hi, I tried to train the model with new dataset which have about 60000 nodes,
but I have a problem of getting Killed suddenly. Do you have any idea why?
Thanks :)
![image](https://user-images.githubusercontent.com/44370759/82296858-cf736800-99ec-11ea-9b4d-23671c8bce6f.png)

**Comment by benedekrozemberczki** [comment]
Read the paper please and have some understanding of the memory complexity.
