### ISSUE TITLE
miscalculations of normalized adjacency matrix

### ISSUE THREAD

**Issue by neilctwu** [benedekrozemberczki/AttentionWalk#9]
Thanks for sharing this awesome repo.

The issue is I found that `loss_on_target` will become extreme big while training from the original code, and I think is due to the miscalculation of `normalized_adjacency_matrix `.

From your original code, normalized_adjacency_matrix is been calculated by:
```
normalized_adjacency_matrix = degs.dot(adjacency_matrix)
```
However while the matrix hasn't been normalize but simply multiple by degree of nodes.
I think the part of normalized_adjacency_matrix should be modified like its original definition:
```
  normalized_adjacency_matrix = degs.power(-1/2)\
                                    .dot(adjacency_matrix)\
                                    .dot(degs.power(-1/2))
```
It'll turn out to be more reasonable loss shown below:
![image](https://user-images.githubusercontent.com/53163710/122146213-9593c000-ce91-11eb-9498-20a0b4268117.png)

Am I understand it correctly?

**Comment by benedekrozemberczki** [comment]
HI there @neilctwu,

Can you make a PR which does the division for each node before the multiplication (inverse degrees)?
